---
title: "STAT 412/612 Teaching Website"
author: "David Gerard"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Synopsis

This website contains the teaching materials for STAT 412/612 Statistical 
Programming in R, taught during the Spring semester of 2019 at American 
University by [David Gerard](https://dcgerard.github.io/).

# Administrative

- [Syllabus](./admin/syllabus_412_612.pdf)
- [Tentative Schedule](./admin/schedule.pdf)

# Final Project

- [Description](./admin/final_project.pdf)
- [Progress Report](./admin/progress_report.pdf)

# Lectures

- 01 Introduction:
    - [01 Data Science and R](./lectures/01_intro/01_data_science_and_r.pdf)
    - [01 Good File Organization](./lectures/01_intro/01_file_system.pdf)
    - [01 R Basics and R Markdown](./lectures/01_intro/01_worksheet.pdf)
    - [01 Logicals](./lectures/01_intro/01_logic.pdf)
    - [01 Data Frames](./lectures/01_intro/01_data_frames.pdf)
    - [01 R Basics Lab](./lectures/01_intro/01_lab.pdf)
- 02 More on Programming
    - [02 Pipes and Functions](./lectures/02_functions_pipes/02_functions_pipes.pdf)
    - [02 Pipes and Functions Lab](./lectures/02_functions_pipes/02_lab.pdf)
    - [02 R Scripts](./lectures/02_functions_pipes/02_scripts.pdf)
- 03 Visualizations
    - [03 Visualization with ggplot2](./lectures/03_graphics/03_graphics.pdf)
    - [03 Visualization Lab](./lectures/03_graphics/03_lab_2.pdf)
    - [03 `qplot()` Cheat Sheet](./lectures/03_graphics/03_qplot_cheatsheet.pdf)
    - [03 Base R Graphics Cheat Sheet](./lectures/03_graphics/03_base_r_cheatsheet.pdf)
    - [03 Lattice R Graphics Cheat Sheet](./lectures/03_graphics/03_lattice_cheatsheet.pdf)
    - [03 RStudio's ggplot2 Cheat Sheet](https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf)
    - BBC visualizations use ggplot2: [bbplot](https://github.com/bbc/bbplot), [cookbook](https://bbc.github.io/rcookbook/)
- 04 Manipulating Data Frames
    - [04 Manipulating Data Frames with dplyr](./lectures/04_dplyr/04_dplyr.pdf)
    - [04 dplyr Lab](./lectures/04_dplyr/04_dplyr_lab.pdf)
- 05 Data Import and EDA
    - [05 Data Import](./lectures/05_eda/05_data_import.pdf)
    - [05 Recoding Variable Values](./lectures/05_eda/05_recoding.pdf)
    - [05 EDA Basics](./lectures/05_eda/05_eda.pdf)
    - [05 EDA Exercise](./lectures/05_eda/05_eda_exercise.pdf)
- [Mid-semester Debugging Advice](./lectures/common_coding_issues.pdf)
- 06 Tidy Data
    - [06 Parsers](./lectures/06_tidyr/06_parsers.pdf)
    - [06 tidyr](./lectures/06_tidyr/06_tidyr.pdf)
    - [06 tidyr Lab](./lectures/06_tidyr/06_tidyr_lab.pdf)
- 07 Relational Data
    - [07 Joining](./lectures/07_joining/07_joining.pdf)
    - [07 Databases and dbplyr](./lectures/07_joining/07_dbplyr.pdf)
    - [07 Relational Data Lab](./lectures/07_joining/07_joining_lab.pdf)
- 08 Strings and Regular Expressions
    - [08 Strings and Regular Expressions](./lectures/08_strings/08_strings.pdf)
    - [08 Strings Lab](./lectures/08_strings/08_strings_lab.pdf)
- 09 Factors
    - [09 Factors](./lectures/09_factors/09_factors.pdf)
    - [09 Factors Lab](./lectures/09_factors/09_factors_lab.pdf)
    - [McNamara and Horton (2017)](./lectures/09_factors/mcnamara_horton_2017.pdf)
- 10 Dates
    - [10 Dates](./lectures/10_dates/10_dates.pdf)
    - [10 Dates Lab](./lectures/10_dates/10_dates_lab.pdf)
- 11 Vectors and Iterators
    - [11 Vectors and Lists](./lectures/11_vectors_iterators/11_vectors.pdf)
    - [11 Iterators](./lectures/11_vectors_iterators/11_iterators.pdf)
    - [11 Vectors/Iterators Lab](./lectures/11_vectors_iterators/11_vectors_iterators_lab.pdf)
- 12 Presentations
    - [12 Presentations with R Markdown (PDF)](./lectures/12_presentations/12_presentations.pdf)
    - [12 Presentations with R Markdown (revealjs)](./lectures/12_presentations/12_presentations.html)
