---
title: "Tentative Course Plan for STAT 412/612"
author: "David Gerard"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: "blue"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo       = TRUE, 
                      fig.height = 3, 
                      fig.width  = 6,
                      fig.align  = "center")
```

- Week 1: 01/16
    - Chapters 1, 2, 4, 10, and 27 of [RDS](https://r4ds.had.co.nz/)
    - Install all tools for the semester.
    - R in the context of Data Science.
    - Proper file system organization.
    - Basics of R
    - Basics of R Markdown
    - Data Frames
    - Logicals
- Week 2: 01/23
    - Chapters 6, 17, 18, and 19 of [RDS](https://r4ds.had.co.nz/)
    - Using pipes (magrittr)
    - Creating functions
    - R Scripts
- Week 3:  01/30
    - Chapter 3 of [RDS](https://r4ds.had.co.nz/)
    - Data visualization and ggplot2.
- Week 4: 02/06
    - Chapter 5 of [RDS](https://r4ds.had.co.nz/)
    - Manipulating data frames.
    - Calculating summary statistics.
    - dplyr
- Week 5: 02/13
    - Chapters 7 and 11 of [RDS](https://r4ds.had.co.nz/)
    - Data import/export.
    - Exploratory Data Analysis (EDA).
    - EDA exercise.
- Week 6: 02/20
    - Midterm exam covering weeks 1 through 4.
- Week 7: 02/27
    - Chapter 12 of [RDS](https://r4ds.had.co.nz/)
    - Tidying data
    - tidyr
- Week 8: 03/06
    - Chapter 13 of [RDS](https://r4ds.had.co.nz/)
    - Relational Data
    - SQL?
- NO CLASS ON 03/13 (Spring Break)
- Week 9: 03/20
    - [Git Appendix in r-pkgs](http://r-pkgs.had.co.nz/git.html)
    - [Happy git with R](https://happygitwithr.com/)
    - [Setting up GitHub Classroom](https://github.com/jfiksel/github-classroom-for-students)
    - Git and GitHub.
- Week 10: 03/27
    - Chapter 14 of [RDS](https://r4ds.had.co.nz/)
    - Strings and regular expressions
- Week 11: 04/03
    - Midterm exam covering weeks 5, 7, 8, 9, and 10.
- Week 12: 04/10
    - Chapters 15 and 16 of [RDS](https://r4ds.had.co.nz/)
    - Factors (forcats)
    - Dates/Times (lubridate)
- Week 13: 04/17
    - TBD. Possible topics:
        - Make your own website (personal/project) in R (Chapter 10 of 
          [R Markdown Book](https://bookdown.org/yihui/rmarkdown/)). 
        - Making presentations using R Markdown (Chapter 4 or 
          [R Markdown Book](https://bookdown.org/yihui/rmarkdown/)).
        - Plotting spatial data in R (Chapter 9 of 
          [Case Studies Book](https://eriqande.github.io/rep-res-eeb-2017/plotting-spatial-data-with-ggplot.html)).
        - Linear/Logistic Regression in R.
- Week 14: 04/24
    - Project Presentations
- FINAL EXAM ON 05/01
    
    
